"""jsdh

Revision ID: 43167fbc83d3
Revises: 
Create Date: 2024-11-19 12:16:00.813937

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43167fbc83d3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tecnico',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=True),
    sa.Column('especialidade', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('projeto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=True),
    sa.Column('ano_inicio', sa.Integer(), nullable=True),
    sa.Column('id_tecnico', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_tecnico'], ['tecnico.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('projeto')
    op.drop_table('tecnico')
    # ### end Alembic commands ###
